Computing dependencies
Analyzing 180 sources with 6 local dependencies
ninja: Entering directory `output/openai__gym'
[1/211] check gym.utils.colorize
[2/211] check gym.version
[3/211] infer gym.utils.EzPickle
[4/211] check tests.gym.__init__
[5/211] check tests.gym.envs.robotics.hand.__init__
[6/211] check gym.spaces.tests.__init__
[7/211] check gym.wrappers.tests.__init__
[8/211] check gym.utils.ezpickle
[9/211] check gym.envs.tests.__init__
[10/211] check tests.gym.wrappers.__init__
[11/211] check tests.__init__
[12/211] check gym.envs.algorithmic.tests.__init__
[13/211] check gym.vector.tests.__init__
[14/211] check gym.wrappers.monitoring.tests.__init__
[15/211] check gym.envs.robotics.hand.__init__
[16/211] check gym.utils.json_utils
[17/211] check tests.gym.envs.__init__
[18/211] check tests.gym.envs.robotics.__init__
[19/211] check gym.wrappers.monitoring.__init__
[20/211] check gym.envs.robotics.fetch.__init__
[21/211] check gym.envs.box2d.car_dynamics
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/pyi/gym/envs/box2d/car_dynamics.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/imports/gym.envs.box2d.car_dynamics.imports --module-name gym.envs.box2d.car_dynamics -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/pyi/gym/envs/box2d/car_dynamics.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/gym/envs/box2d/car_dynamics.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/gym/envs/box2d/car_dynamics.py", line 12, in <module>: Can't find module 'Box2D'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/gym/envs/box2d/car_dynamics.py", line 13, in <module>: Can't find module 'Box2D.b2'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[22/211] check setup
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/pyi/setup.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/imports/setup.imports --module-name setup -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/pyi/setup.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/setup.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/setup.py", line 8, in <module>: Can't find module 'version'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[23/211] check gym.utils.atomic_write
[24/211] check gym.utils.__init__
[25/211] check gym.vector.utils.misc
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/pyi/gym/vector/utils/misc.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/imports/gym.vector.utils.misc.imports --module-name gym.vector.utils.misc -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/pyi/gym/vector/utils/misc.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/gym/vector/utils/misc.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/gym/vector/utils/misc.py", line 12, in __getstate__: Can't find module 'cloudpickle'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[26/211] check gym.error
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/pyi/gym/error.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/imports/gym.error.imports --module-name gym.error -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/pyi/gym/error.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/gym/error.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/gym/error.py", line 126, in __str__: Name 'unicode' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[27/211] check gym.utils.closer
[28/211] check gym.wrappers.monitoring.tests.helpers
[29/211] check gym.envs.robotics.rotations
[30/211] check gym.logger
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/pyi/gym/logger.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/imports/gym.logger.imports --module-name gym.logger -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/openai__gym/pyi/gym/logger.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/gym/logger.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/gym/logger.py", line 34, in warn: 'gym.utils.colorize' object is not callable [not-callable]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/openai__gym/gym/logger.py", line 39, in error: 'gym.utils.colorize' object is not callable [not-callable]

For more details, see https://google.github.io/pytype/errors.html#not-callable
ninja: build stopped: subcommand failed.
Leaving directory 'output/openai__gym'
